//   Copyright 2026 JordanD2.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

package io.github.jordand2.tb2_swing.swing_gui;

/**
 *
 * @author jordan
 */
public class NewPortDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewPortDialog.class.getName());
    
    Canvas canvas;
    DrawModule moduleTarget;
    DrawPort portTarget;
    
    /**
     * Creates new form RenameModuleDialog
     */
    public NewPortDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(okButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        portNameLabel = new javax.swing.JLabel();
        portNameField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        portRadButton = new javax.swing.JRadioButton();
        exportRadButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        dataTypeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        portNameLabel.setText("Port Name :");

        portNameField.setText("analysis_export");

        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        buttonGroup1.add(portRadButton);
        portRadButton.setText("port");

        buttonGroup1.add(exportRadButton);
        exportRadButton.setSelected(true);
        exportRadButton.setText("export");

        jLabel1.setText("Data Type :");

        dataTypeField.setText("int");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(portNameLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(okButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)
                                .addContainerGap(95, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(portNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(portRadButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exportRadButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dataTypeField))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portNameLabel)
                    .addComponent(portNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dataTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portRadButton)
                    .addComponent(exportRadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (portTarget != null) {
            moduleTarget = portTarget.parent;
            
            int selectedType;
            if (portRadButton.isSelected()) {
                selectedType = DrawPort.OUTPUT_PORT;
            } else {
                selectedType = DrawPort.INPUT_PORT;
            }
            
            if (portTarget.dataType.equals(dataTypeField.getText()) && portTarget.type == selectedType) {
                // Simple rename -> don't delete the connections
                portTarget.name = portNameField.getText();
            } else {
                // Changed dataType or direction -> delete and recreate the port
                moduleTarget.deletePort(portTarget);
                if (portTarget.type == selectedType) {
                    // Same direction -> preserve idx
                    moduleTarget.addPort(portNameField.getText(), dataTypeField.getText(), selectedType, portTarget.idx);
                } else {
                    // Changed direction -> reindex
                    moduleTarget.addPort(portNameField.getText(), dataTypeField.getText(), selectedType);
                }
            }
        } else {
            if (portRadButton.isSelected()) {
                moduleTarget.addPort(portNameField.getText(), dataTypeField.getText(), DrawPort.OUTPUT_PORT);
            } else {
                moduleTarget.addPort(portNameField.getText(), dataTypeField.getText(), DrawPort.INPUT_PORT);
            }
        }
        canvas.repaint();
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    public void usePortInfo(DrawPort port) {
        portNameField.setText(port.name);
        dataTypeField.setText(port.dataType);
        if (port.type == DrawPort.OUTPUT_PORT) {
            portRadButton.setSelected(true);
            exportRadButton.setSelected(false);
        } else {
            portRadButton.setSelected(false);
            exportRadButton.setSelected(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    javax.swing.JTextField dataTypeField;
    javax.swing.JRadioButton exportRadButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    javax.swing.JTextField portNameField;
    private javax.swing.JLabel portNameLabel;
    javax.swing.JRadioButton portRadButton;
    // End of variables declaration//GEN-END:variables
}
