//   Copyright 2026 JordanD2.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

package io.github.jordand2.tb2_swing.swing_gui;

import io.github.jordand2.tb2_swing.core.Module;
import io.github.jordand2.tb2_swing.yamlio.YamlReader;
import io.github.jordand2.tb2_swing.yamlio.YamlWriter;
import io.github.jordand2.tb2_swing.jte_render.ModuleRenderer;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Graphics2D;
import java.awt.desktop.QuitStrategy;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jordan
 */
public class Tb2Swing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tb2Swing.class.getName());
    
    /**
     * Creates new form NewJFrame
     */
    public Tb2Swing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        renderBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        canvas = new Canvas();
        appMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newItem = new javax.swing.JMenuItem();
        openItem = new javax.swing.JMenuItem();
        fileSeparator1 = new javax.swing.JPopupMenu.Separator();
        saveItem = new javax.swing.JMenuItem();
        saveAsItem = new javax.swing.JMenuItem();
        fileSeparator2 = new javax.swing.JPopupMenu.Separator();
        exportImageItem = new javax.swing.JMenuItem();
        fileSeparator3 = new javax.swing.JPopupMenu.Separator();
        printItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoItem = new javax.swing.JMenuItem();
        redoItem = new javax.swing.JMenuItem();
        editSeparator1 = new javax.swing.JPopupMenu.Separator();
        cutItem = new javax.swing.JMenuItem();
        copyItem = new javax.swing.JMenuItem();
        duplicateItem = new javax.swing.JMenuItem();
        pasteItem = new javax.swing.JMenuItem();
        deleteItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        zoomInItem = new javax.swing.JMenuItem();
        zoomOutItem = new javax.swing.JMenuItem();
        zoomFitItem = new javax.swing.JMenuItem();
        resetViewportItem = new javax.swing.JMenuItem();
        runMenu = new javax.swing.JMenu();
        validateItem = new javax.swing.JMenuItem();
        runSeparator1 = new javax.swing.JPopupMenu.Separator();
        renderItem = new javax.swing.JMenuItem();
        windowMenu = new javax.swing.JMenu();
        previewTypeItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TB2");
        setBounds(new java.awt.Rectangle(0, 25, 1000, 800));
        setMinimumSize(new java.awt.Dimension(525, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        addBtn.setMnemonic('A');
        addBtn.setText("Add");
        addBtn.setFocusable(false);
        addBtn.addActionListener(this::addBtnActionPerformed);
        toolBar.add(addBtn);

        newBtn.setMnemonic('N');
        newBtn.setText("New");
        newBtn.setFocusable(false);
        newBtn.addActionListener(this::newBtnActionPerformed);
        toolBar.add(newBtn);

        loadBtn.setMnemonic('O');
        loadBtn.setText("Load");
        loadBtn.setFocusable(false);
        loadBtn.addActionListener(this::loadBtnActionPerformed);
        toolBar.add(loadBtn);

        saveBtn.setMnemonic('S');
        saveBtn.setText("Save");
        saveBtn.setFocusable(false);
        saveBtn.addActionListener(this::saveBtnActionPerformed);
        toolBar.add(saveBtn);

        renderBtn.setMnemonic('R');
        renderBtn.setText("Render");
        renderBtn.setFocusable(false);
        renderBtn.addActionListener(this::renderBtnActionPerformed);
        toolBar.add(renderBtn);

        exitBtn.setMnemonic('Q');
        exitBtn.setText("Quit");
        exitBtn.setFocusable(false);
        exitBtn.addActionListener(this::exitBtnActionPerformed);
        toolBar.add(exitBtn);

        canvas.setBackground(new java.awt.Color(255, 255, 255));
        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                canvasMouseDragged(evt);
            }
        });
        canvas.addMouseWheelListener(this::canvasMouseWheelMoved);
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                canvasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canvasMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        newItem.setAccelerator(KeyStroke.getKeyStroke('N', Canvas.EDIT_MODIFIER_MASK)
        );
        newItem.setText("New");
        newItem.setEnabled(false);
        fileMenu.add(newItem);

        openItem.setAccelerator(KeyStroke.getKeyStroke('O', Canvas.EDIT_MODIFIER_MASK)
        );
        openItem.setText("Open");
        openItem.setToolTipText("");
        openItem.addActionListener(this::openItemActionPerformed);
        fileMenu.add(openItem);
        fileMenu.add(fileSeparator1);

        saveItem.setAccelerator(KeyStroke.getKeyStroke('S', Canvas.EDIT_MODIFIER_MASK));
        saveItem.setText("Save");
        saveItem.setEnabled(false);
        saveItem.addActionListener(this::saveItemActionPerformed);
        fileMenu.add(saveItem);

        saveAsItem.setAccelerator(KeyStroke.getKeyStroke('S', Canvas.EDIT_MODIFIER_MASK | InputEvent.SHIFT_MASK));
        saveAsItem.setText("Save As...");
        saveAsItem.addActionListener(this::saveAsItemActionPerformed);
        fileMenu.add(saveAsItem);
        fileMenu.add(fileSeparator2);

        exportImageItem.setAccelerator(KeyStroke.getKeyStroke('P', Canvas.EDIT_MODIFIER_MASK | InputEvent.SHIFT_MASK));
        exportImageItem.setText("Export image");
        exportImageItem.addActionListener(this::exportImageItemActionPerformed);
        fileMenu.add(exportImageItem);
        fileMenu.add(fileSeparator3);

        printItem.setAccelerator(KeyStroke.getKeyStroke('P', Canvas.EDIT_MODIFIER_MASK));
        printItem.setText("Print");
        printItem.setEnabled(false);
        fileMenu.add(printItem);

        appMenuBar.add(fileMenu);

        editMenu.setText("Edit");

        undoItem.setAccelerator(KeyStroke.getKeyStroke('Z', Canvas.EDIT_MODIFIER_MASK));
        undoItem.setText("Undo");
        undoItem.setEnabled(false);
        editMenu.add(undoItem);

        redoItem.setAccelerator(KeyStroke.getKeyStroke('Y', Canvas.EDIT_MODIFIER_MASK));
        redoItem.setText("Redo");
        redoItem.setEnabled(false);
        editMenu.add(redoItem);
        editMenu.add(editSeparator1);

        cutItem.setAccelerator(KeyStroke.getKeyStroke('X', Canvas.EDIT_MODIFIER_MASK));
        cutItem.setText("Cut");
        editMenu.add(cutItem);

        copyItem.setAccelerator(KeyStroke.getKeyStroke('C', Canvas.EDIT_MODIFIER_MASK));
        copyItem.setText("Copy");
        editMenu.add(copyItem);

        duplicateItem.setAccelerator(KeyStroke.getKeyStroke('D', Canvas.EDIT_MODIFIER_MASK));
        duplicateItem.setText("Duplicate");
        editMenu.add(duplicateItem);

        pasteItem.setAccelerator(KeyStroke.getKeyStroke('V', Canvas.EDIT_MODIFIER_MASK));
        pasteItem.setText("Paste");
        editMenu.add(pasteItem);

        deleteItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        deleteItem.setText("Delete");
        editMenu.add(deleteItem);

        appMenuBar.add(editMenu);

        jMenu1.setText("View");

        zoomInItem.setAccelerator(KeyStroke.getKeyStroke('=', Canvas.EDIT_MODIFIER_MASK));
        zoomInItem.setText("Zoom In");
        zoomInItem.addActionListener(this::zoomInItemActionPerformed);
        jMenu1.add(zoomInItem);

        zoomOutItem.setAccelerator(KeyStroke.getKeyStroke('-', Canvas.EDIT_MODIFIER_MASK));
        zoomOutItem.setText("Zoom Out");
        zoomOutItem.addActionListener(this::zoomOutItemActionPerformed);
        jMenu1.add(zoomOutItem);

        zoomFitItem.setAccelerator(KeyStroke.getKeyStroke('0', Canvas.EDIT_MODIFIER_MASK));
        zoomFitItem.setText("Zoom Fit");
        zoomFitItem.setEnabled(false);
        zoomFitItem.addActionListener(this::zoomFitItemActionPerformed);
        jMenu1.add(zoomFitItem);

        resetViewportItem.setText("Reset Viewport");
        resetViewportItem.addActionListener(this::resetViewportItemActionPerformed);
        jMenu1.add(resetViewportItem);

        appMenuBar.add(jMenu1);

        runMenu.setText("Run");

        validateItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        validateItem.setText("Validate");
        validateItem.addActionListener(this::validateItemActionPerformed);
        runMenu.add(validateItem);
        runMenu.add(runSeparator1);

        renderItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        renderItem.setText("Render");
        renderItem.addActionListener(this::renderItemActionPerformed);
        runMenu.add(renderItem);

        appMenuBar.add(runMenu);

        windowMenu.setText("Window");

        previewTypeItem.setText("Preview Type");
        previewTypeItem.addActionListener(this::previewTypeItemActionPerformed);
        windowMenu.add(previewTypeItem);

        appMenuBar.add(windowMenu);

        setJMenuBar(appMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File lastImageDir;
    File lastModuleDir = Path.of("modules").toFile();
    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
        if (canvas instanceof Canvas c) {
            Module top = c.getTopAsModule();
            if (top == null) {
                logger.log(Level.INFO, "Can't save empty canvas!");
                return;
            }
            
            JFileChooser jfc = new JFileChooser(lastModuleDir);
            jfc.setSelectedFile(new File(lastModuleDir, String.format("%s.yaml", top.getName())));
            if (jfc.showSaveDialog(saveBtn) == JFileChooser.APPROVE_OPTION) {
                lastModuleDir = jfc.getCurrentDirectory();
                
                YamlWriter writer = new YamlWriter();
                writer.writeModule(jfc.getSelectedFile(), top);
                c.modified = false;
            } 
        }
    }//GEN-LAST:event_saveBtnActionPerformed
    
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        formWindowClosing(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitBtnActionPerformed

    private void canvasMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_canvasMouseWheelMoved
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas)canvas;
            c.handleMouseWheelEvent(evt);
        }
    }//GEN-LAST:event_canvasMouseWheelMoved

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas)canvas;
            c.addModule(new DrawModule(c, "module", new RealPoint(c.getWidth()/2, c.getHeight()/2).inverseScaleBy(c.scaleFactor).add(c.offset), new RealPoint(100, 100)));
            c.repaint();
        }
    }//GEN-LAST:event_addBtnActionPerformed
    
    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas)canvas;
            c.resetViewport();
        }
    }//GEN-LAST:event_newBtnActionPerformed

    private void canvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseClicked
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas) canvas;
            c.handleMouseClickEvent(evt);
        }
    }//GEN-LAST:event_canvasMouseClicked
    
    private void canvasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseDragged
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas) canvas;
            c.handleMouseDraggedEvent(evt);
        }
    }//GEN-LAST:event_canvasMouseDragged

    private void canvasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMousePressed
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas) canvas;
            c.handleMousePressedEvent(evt);
        }
    }//GEN-LAST:event_canvasMousePressed

    private void canvasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseReleased
        if (canvas instanceof Canvas c) {
            c.handleMouseReleasedEvent(evt);
        }
    }//GEN-LAST:event_canvasMouseReleased
    
    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        if (canvas instanceof Canvas c) {
            JFileChooser jfc = new JFileChooser(lastModuleDir);
            jfc.setFileFilter(new FileNameExtensionFilter("Yaml files", "yaml"));
            if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File f = jfc.getSelectedFile();
                lastModuleDir = jfc.getCurrentDirectory();
                
                YamlReader reader = new YamlReader();
                Module module = reader.readModule(f);
                if (module != null) {
                    c.loadModule(reader.readModule(f));
                }
            }
        }
    }//GEN-LAST:event_loadBtnActionPerformed

    File lastRenderDir = new File(".");
    
    private void renderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderBtnActionPerformed
        if (canvas instanceof Canvas c) {
            
            Module top = c.getTopAsModule();
            if (top == null) {
                logger.log(Level.INFO, "Can't render empty canvas!");
                return;
            }
            
            JFileChooser jfc = new JFileChooser();
            jfc.setMultiSelectionEnabled(false);
            if (lastRenderDir != null) {
                jfc.setSelectedFile(lastRenderDir);
            }
            jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            jfc.setAcceptAllFileFilterUsed(false);

            if (jfc.showDialog(this, "Render!") == JFileChooser.APPROVE_OPTION) {
                ModuleRenderer moduleRenderer = new ModuleRenderer();
                String outputPath;
                if (jfc.getSelectedFile().isDirectory()) {
                    outputPath = jfc.getSelectedFile().getPath();
                } else {
                    outputPath = jfc.getSelectedFile().getParent();
                }
                try {
                    moduleRenderer.renderTopModule(top, outputPath);
                } catch (IOException ioe) {
                    logger.log(Level.SEVERE, String.format("Failed to write file '%s/%s.sv'!", outputPath, top.type));
                }
                lastRenderDir = new File(outputPath);
            } 
        }
    }//GEN-LAST:event_renderBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        logger.log(Level.INFO, "Closing window");
        
        if (canvas instanceof Canvas c && c.modified) {
            if (JOptionPane.showConfirmDialog(this, "Save before exit?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                saveBtnActionPerformed(new ActionEvent(evt.getSource(), ActionEvent.ACTION_PERFORMED, "Save"));
                
                if (c.modified) {
                    return; // cancel exit request
                }
            }
        }
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void openItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openItemActionPerformed
        loadBtnActionPerformed(evt);
    }//GEN-LAST:event_openItemActionPerformed

    private void saveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemActionPerformed
        saveBtnActionPerformed(evt);
    }//GEN-LAST:event_saveItemActionPerformed

    private void validateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateItemActionPerformed
        if (canvas instanceof Canvas c) {
            if (c.validateModules()) {
                logger.log(Level.INFO, "Validation Passed!");
            } else {
                logger.log(Level.INFO, "Validation Failed!");
            }
        }
    }//GEN-LAST:event_validateItemActionPerformed

    private void renderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderItemActionPerformed
        renderBtnActionPerformed(evt);
    }//GEN-LAST:event_renderItemActionPerformed

    private void exportImageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportImageItemActionPerformed
        JFileChooser jfc = new JFileChooser(lastImageDir);
        if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selected = jfc.getSelectedFile();
            String path = selected.getPath();
            if (!path.endsWith(".png")) {
                selected = new File(path + ".png");
            }
            BufferedImage image = new BufferedImage(canvas.getWidth(), canvas.getHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = image.createGraphics();
            canvas.printAll(g2d);
            g2d.dispose();
            try {
                // TODO : draw all components wrapped by some fixed margin. Image should be the same regardless of zoom distance or window location
                ImageIO.write(image, "png", selected);
            } catch (IOException e) {
                logger.log(Level.SEVERE, String.format("Failed to save %s", selected.getPath()));
            }
            lastImageDir = selected.getParentFile();
        }
    }//GEN-LAST:event_exportImageItemActionPerformed

    private void zoomInItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomInItemActionPerformed
        if (canvas instanceof Canvas c) {
            c.handleZoom(-Canvas.KEYBOARD_ZOOM_STEP, c.getWidth()/2, c.getHeight()/2);
            c.repaint();
        }
    }//GEN-LAST:event_zoomInItemActionPerformed

    private void zoomOutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOutItemActionPerformed
        if (canvas instanceof Canvas c) {
            c.handleZoom(Canvas.KEYBOARD_ZOOM_STEP, c.getWidth()/2, c.getHeight()/2);
            c.repaint();
        }
    }//GEN-LAST:event_zoomOutItemActionPerformed

    private void zoomFitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomFitItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoomFitItemActionPerformed

    private void resetViewportItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetViewportItemActionPerformed
        if (canvas instanceof Canvas c) {
            c.resetViewport();
            c.repaint();
        }
    }//GEN-LAST:event_resetViewportItemActionPerformed

    private void saveAsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsItemActionPerformed
        saveBtnActionPerformed(evt);
    }//GEN-LAST:event_saveAsItemActionPerformed

    private void previewTypeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewTypeItemActionPerformed
        JFileChooser jfc = new JFileChooser(lastModuleDir);
        jfc.setFileFilter(new FileNameExtensionFilter("Yaml files", "yaml"));
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            lastModuleDir = jfc.getCurrentDirectory();

            YamlReader reader = new YamlReader();
            Module module = reader.readModule(f);
            if (module != null) {
                JFrame typeEditorFrame = new JFrame();
                
                TypeEditorPanel typeEditor = new TypeEditorPanel();
                typeEditor.setBackground(Color.WHITE);
                typeEditor.setPreferredSize(new Dimension(500, 500));
                
                typeEditorFrame.add(typeEditor);
                typeEditorFrame.setPreferredSize(new Dimension(500, 500));
                
                typeEditorFrame.pack();
                typeEditor.loadModule(module);
                
                EventQueue.invokeLater(() -> {
                    typeEditorFrame.setVisible(true);
                });
            }
        }
        
        
    }//GEN-LAST:event_previewTypeItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // TODO: Does this make non-Mac environments act weird
        System.setProperty("apple.laf.useScreenMenuBar", "true");

        Desktop.getDesktop().setPreferencesHandler((e) -> {
            // TODO: Add preferences window. Migrate constants from Canvas to the preferences system
            logger.log(Level.INFO, "Requested preferences");
        });
        
        Tb2Swing app = new Tb2Swing();
        
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.APP_QUIT_STRATEGY)) {
            Desktop.getDesktop().setQuitStrategy(QuitStrategy.CLOSE_ALL_WINDOWS);
        }
        
        java.awt.EventQueue.invokeLater(() -> app.setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JMenuBar appMenuBar;
    private javax.swing.JPanel canvas;
    private javax.swing.JMenuItem copyItem;
    private javax.swing.JMenuItem cutItem;
    private javax.swing.JMenuItem deleteItem;
    private javax.swing.JMenuItem duplicateItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JPopupMenu.Separator editSeparator1;
    private javax.swing.JButton exitBtn;
    private javax.swing.JMenuItem exportImageItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator fileSeparator1;
    private javax.swing.JPopupMenu.Separator fileSeparator2;
    private javax.swing.JPopupMenu.Separator fileSeparator3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton newBtn;
    private javax.swing.JMenuItem newItem;
    private javax.swing.JMenuItem openItem;
    private javax.swing.JMenuItem pasteItem;
    private javax.swing.JMenuItem previewTypeItem;
    private javax.swing.JMenuItem printItem;
    private javax.swing.JMenuItem redoItem;
    private javax.swing.JButton renderBtn;
    private javax.swing.JMenuItem renderItem;
    private javax.swing.JMenuItem resetViewportItem;
    private javax.swing.JMenu runMenu;
    private javax.swing.JPopupMenu.Separator runSeparator1;
    private javax.swing.JMenuItem saveAsItem;
    private javax.swing.JButton saveBtn;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JPanel toolBar;
    private javax.swing.JMenuItem undoItem;
    private javax.swing.JMenuItem validateItem;
    private javax.swing.JMenu windowMenu;
    private javax.swing.JMenuItem zoomFitItem;
    private javax.swing.JMenuItem zoomInItem;
    private javax.swing.JMenuItem zoomOutItem;
    // End of variables declaration//GEN-END:variables
}
