//   Copyright 2026 JordanD2.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

package io.github.jordand2.tb2_swing.swing_gui;

import io.github.jordand2.tb2_swing.core.Module;
import io.github.jordand2.tb2_swing.yamlio.YamlReader;
import io.github.jordand2.tb2_swing.yamlio.YamlWriter;
import io.github.jordand2.tb2_swing.jte_render.ModuleRenderer;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jordan
 */
public class Tb2Swing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tb2Swing.class.getName());
    
    /**
     * Creates new form NewJFrame
     */
    public Tb2Swing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        renderBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        canvas = new Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TB2");
        setBounds(new java.awt.Rectangle(0, 25, 1000, 800));
        setMinimumSize(new java.awt.Dimension(525, 200));

        addBtn.setMnemonic('A');
        addBtn.setText("Add");
        addBtn.setFocusable(false);
        addBtn.addActionListener(this::addBtnActionPerformed);
        toolBar.add(addBtn);

        newBtn.setMnemonic('N');
        newBtn.setText("New");
        newBtn.setFocusable(false);
        newBtn.addActionListener(this::newBtnActionPerformed);
        toolBar.add(newBtn);

        loadBtn.setMnemonic('O');
        loadBtn.setText("Load");
        loadBtn.setFocusable(false);
        loadBtn.addActionListener(this::loadBtnActionPerformed);
        toolBar.add(loadBtn);

        saveBtn.setMnemonic('S');
        saveBtn.setText("Save");
        saveBtn.setFocusable(false);
        saveBtn.addActionListener(this::saveBtnActionPerformed);
        toolBar.add(saveBtn);

        renderBtn.setMnemonic('R');
        renderBtn.setText("Render");
        renderBtn.setFocusable(false);
        renderBtn.addActionListener(this::renderBtnActionPerformed);
        toolBar.add(renderBtn);

        exitBtn.setMnemonic('Q');
        exitBtn.setText("Quit");
        exitBtn.setFocusable(false);
        exitBtn.addActionListener(this::exitBtnActionPerformed);
        toolBar.add(exitBtn);

        canvas.setBackground(new java.awt.Color(255, 255, 255));
        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                canvasMouseDragged(evt);
            }
        });
        canvas.addMouseWheelListener(this::canvasMouseWheelMoved);
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                canvasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canvasMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File lastModuleDir = Path.of("modules").toFile();
    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
        if (canvas instanceof Canvas c) {
            Module top = c.getTopAsModule();
            if (top == null) {
                logger.log(Level.INFO, "Can't save empty canvas!");
                return;
            }
            
            JFileChooser jfc = new JFileChooser(lastModuleDir);
            jfc.setSelectedFile(new File(lastModuleDir, String.format("%s.yaml", top.getName())));
            if (jfc.showSaveDialog(saveBtn) == JFileChooser.APPROVE_OPTION) {
                lastModuleDir = jfc.getCurrentDirectory();
                
                YamlWriter writer = new YamlWriter();
                writer.writeModule(jfc.getSelectedFile(), top);
            } 
        }
    }//GEN-LAST:event_saveBtnActionPerformed
    
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void canvasMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_canvasMouseWheelMoved
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas)canvas;
            c.handleMouseWheelEvent(evt);
        }
    }//GEN-LAST:event_canvasMouseWheelMoved

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas)canvas;
            c.modules.add(new DrawModule(c, "module", new RealPoint(c.getWidth()/2, c.getHeight()/2).inverseScaleBy(c.scaleFactor).add(c.offset), new RealPoint(100, 100)));
            c.repaint();
        }
    }//GEN-LAST:event_addBtnActionPerformed
    
    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas)canvas;
            c.resetViewport();
        }
    }//GEN-LAST:event_newBtnActionPerformed

    private void canvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseClicked
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas) canvas;
            c.handleMouseClickEvent(evt);
        }
    }//GEN-LAST:event_canvasMouseClicked
    
    private void canvasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseDragged
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas) canvas;
            c.handleMouseDraggedEvent(evt);
        }
    }//GEN-LAST:event_canvasMouseDragged

    private void canvasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMousePressed
        if (canvas instanceof Canvas) {
            Canvas c = (Canvas) canvas;
            c.handleMousePressedEvent(evt);
        }
    }//GEN-LAST:event_canvasMousePressed

    private void canvasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseReleased
        if (canvas instanceof Canvas c) {
            c.handleMouseReleasedEvent(evt);
        }
    }//GEN-LAST:event_canvasMouseReleased
    
    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        if (canvas instanceof Canvas c) {
            JFileChooser jfc = new JFileChooser(lastModuleDir);
            jfc.setFileFilter(new FileNameExtensionFilter("Yaml files", "yaml"));
            if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File f = jfc.getSelectedFile();
                lastModuleDir = jfc.getCurrentDirectory();
                
                YamlReader reader = new YamlReader();
                Module module = reader.readModule(f);
                if (module != null) {
                    c.loadModule(reader.readModule(f));
                }
            }
        }
    }//GEN-LAST:event_loadBtnActionPerformed

    File lastRenderDir = new File(".");
    
    private void renderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderBtnActionPerformed
        if (canvas instanceof Canvas c) {
            
            Module top = c.getTopAsModule();
            if (top == null) {
                logger.log(Level.INFO, "Can't render empty canvas!");
                return;
            }
            
            JFileChooser jfc = new JFileChooser();
            jfc.setMultiSelectionEnabled(false);
            if (lastRenderDir != null) {
                jfc.setSelectedFile(lastRenderDir);
            }
            jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            jfc.setAcceptAllFileFilterUsed(false);

            if (jfc.showDialog(this, "Render!") == JFileChooser.APPROVE_OPTION) {
                ModuleRenderer moduleRenderer = new ModuleRenderer();
                String outputPath;
                if (jfc.getSelectedFile().isDirectory()) {
                    outputPath = jfc.getSelectedFile().getPath();
                } else {
                    outputPath = jfc.getSelectedFile().getParent();
                }
                try {
                    moduleRenderer.renderTopModule(top, outputPath);
                } catch (IOException ioe) {
                    logger.log(Level.SEVERE, String.format("Failed to write file '%s/%s.sv'!", outputPath, top.type));
                }
                lastRenderDir = new File(outputPath);
            } 
        }
    }//GEN-LAST:event_renderBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tb2Swing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel canvas;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton newBtn;
    private javax.swing.JButton renderBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel toolBar;
    // End of variables declaration//GEN-END:variables
}
